/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ExpiryType = IDL.Variant({
  'thirtyDays' : IDL.Null,
  'ninetyDays' : IDL.Null,
  'twentyMinutes' : IDL.Null,
  'unlimited' : IDL.Null,
});
export const Movie = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'posterUrl' : IDL.Text,
  'videoUrl' : IDL.Text,
});
export const PinCode = IDL.Record({
  'expiresAt' : IDL.Int,
  'code' : IDL.Text,
  'createdAt' : IDL.Int,
  'expiryType' : ExpiryType,
  'isActive' : IDL.Bool,
});

export const idlService = IDL.Service({
  'addMovie' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Record({ 'id' : IDL.Nat, 'ok' : IDL.Bool })],
      [],
    ),
  'adminLogin' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Record({ 'ok' : IDL.Bool, 'token' : IDL.Text })],
      [],
    ),
  'adminLogout' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'checkDeviceToken' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'createPinCode' : IDL.Func(
      [IDL.Text, ExpiryType],
      [IDL.Record({ 'ok' : IDL.Bool, 'code' : IDL.Text })],
      [],
    ),
  'deleteMovie' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
  'getInitialCredentials' : IDL.Func(
      [],
      [IDL.Record({ 'username' : IDL.Text, 'password' : IDL.Text })],
      ['query'],
    ),
  'getMovie' : IDL.Func([IDL.Nat], [IDL.Opt(Movie)], ['query']),
  'getMovies' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Record({ 'total' : IDL.Nat, 'movies' : IDL.Vec(Movie) })],
      ['query'],
    ),
  'listPinCodes' : IDL.Func(
      [IDL.Text],
      [IDL.Record({ 'ok' : IDL.Bool, 'pins' : IDL.Vec(PinCode) })],
      ['query'],
    ),
  'revokePinCode' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'updateAdminCredentials' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'updateMovie' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'validateAdminToken' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'validatePinCode' : IDL.Func(
      [IDL.Text],
      [IDL.Record({ 'ok' : IDL.Bool, 'deviceToken' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ExpiryType = IDL.Variant({
    'thirtyDays' : IDL.Null,
    'ninetyDays' : IDL.Null,
    'twentyMinutes' : IDL.Null,
    'unlimited' : IDL.Null,
  });
  const Movie = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'posterUrl' : IDL.Text,
    'videoUrl' : IDL.Text,
  });
  const PinCode = IDL.Record({
    'expiresAt' : IDL.Int,
    'code' : IDL.Text,
    'createdAt' : IDL.Int,
    'expiryType' : ExpiryType,
    'isActive' : IDL.Bool,
  });
  
  return IDL.Service({
    'addMovie' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Record({ 'id' : IDL.Nat, 'ok' : IDL.Bool })],
        [],
      ),
    'adminLogin' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Record({ 'ok' : IDL.Bool, 'token' : IDL.Text })],
        [],
      ),
    'adminLogout' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'checkDeviceToken' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'createPinCode' : IDL.Func(
        [IDL.Text, ExpiryType],
        [IDL.Record({ 'ok' : IDL.Bool, 'code' : IDL.Text })],
        [],
      ),
    'deleteMovie' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
    'getInitialCredentials' : IDL.Func(
        [],
        [IDL.Record({ 'username' : IDL.Text, 'password' : IDL.Text })],
        ['query'],
      ),
    'getMovie' : IDL.Func([IDL.Nat], [IDL.Opt(Movie)], ['query']),
    'getMovies' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Record({ 'total' : IDL.Nat, 'movies' : IDL.Vec(Movie) })],
        ['query'],
      ),
    'listPinCodes' : IDL.Func(
        [IDL.Text],
        [IDL.Record({ 'ok' : IDL.Bool, 'pins' : IDL.Vec(PinCode) })],
        ['query'],
      ),
    'revokePinCode' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'updateAdminCredentials' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'updateMovie' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'validateAdminToken' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'validatePinCode' : IDL.Func(
        [IDL.Text],
        [IDL.Record({ 'ok' : IDL.Bool, 'deviceToken' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };