/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExpiryType = { 'thirtyDays' : null } |
  { 'ninetyDays' : null } |
  { 'twentyMinutes' : null } |
  { 'unlimited' : null };
export interface Movie {
  'id' : bigint,
  'title' : string,
  'createdAt' : bigint,
  'posterUrl' : string,
  'videoUrl' : string,
}
export interface PinCode {
  'expiresAt' : bigint,
  'code' : string,
  'createdAt' : bigint,
  'expiryType' : ExpiryType,
  'isActive' : boolean,
}
export interface _SERVICE {
  'addMovie' : ActorMethod<
    [string, string, string, string],
    { 'id' : bigint, 'ok' : boolean }
  >,
  'adminLogin' : ActorMethod<
    [string, string],
    { 'ok' : boolean, 'token' : string }
  >,
  'adminLogout' : ActorMethod<[string], boolean>,
  'checkDeviceToken' : ActorMethod<[string], boolean>,
  'createPinCode' : ActorMethod<
    [string, ExpiryType],
    { 'ok' : boolean, 'code' : string }
  >,
  'deleteMovie' : ActorMethod<[string, bigint], boolean>,
  'getInitialCredentials' : ActorMethod<
    [],
    { 'username' : string, 'password' : string }
  >,
  'getMovie' : ActorMethod<[bigint], [] | [Movie]>,
  'getMovies' : ActorMethod<
    [bigint, bigint],
    { 'total' : bigint, 'movies' : Array<Movie> }
  >,
  'listPinCodes' : ActorMethod<
    [string],
    { 'ok' : boolean, 'pins' : Array<PinCode> }
  >,
  'revokePinCode' : ActorMethod<[string, string], boolean>,
  'updateAdminCredentials' : ActorMethod<[string, string, string], boolean>,
  'updateMovie' : ActorMethod<
    [string, bigint, string, string, string],
    boolean
  >,
  'validateAdminToken' : ActorMethod<[string], boolean>,
  'validatePinCode' : ActorMethod<
    [string],
    { 'ok' : boolean, 'deviceToken' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];